config/routes.rb
Rails.application.routes.draw do
  get '/answer', to: 'coaching#answer'

  get '/ask', to: 'coaching#ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController

  def answer
    @question = params[:query]

    @question.last == "?" ? @answer = "Silly question!" : @answer = "I dont care!"
  end

  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1>Answer</h1>
 <!-- Display the question you ask your coach as well as his answer. -->
 <!-- Your question to your coach should be given as a parameter named :query -->

<!-- Display the question you ask your coach -->
<p><%= @question %></p>
<p><%= @answer %></p>
<!-- Display your coach's answer -->

<%= link_to "Ask a new question", ask_path %>

app/views/coaching/ask.html.erb
<h1>Got a question?</h1>

<form action="<%= answer_path %>" method="get">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="query" placeholder="What's your question?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stupidcoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>